sudo: required

services:
  - docker

language: node_js

node_js:
  - node

branches:
  only:
    - master

script:
  - wget https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip
  - unzip terraform_0.12.20_linux_amd64.zip
  - ./terraform --version
  - ./terraform init
  - ./terraform destroy -auto-approve
  - ./terraform apply -auto-approve